### ISSUE TITLE
clojurescript support

### ISSUE THREAD

**Issue by viebel** [weavejester/hashp#6]
Does `hashp` work in Clojurescript?

**Comment by weavejester** [comment]
Not currently, because none of the files are .cljc or cljs. However, there's no reason it couldn't be, as Spyscope works with both and uses the same mechanism.

**Comment by lucywang000** [comment]
I added cljs support in #7 (to be reviewed), cheers!

**Comment by lucywang000** [comment]
@weavejester would you please cut a release to include the cljs support feature?

**Comment by weavejester** [comment]
Released 0.2.0.
