### ISSUE TITLE
How to use with deps.edn?

### ISSUE THREAD

**Issue by kirillsalykin** [weavejester/hashp#8]
It seems that some additional steps should be taken because there is no idea of `injection`/`dev-tool` in clojure deps tools.

Maybe makes sense to specify those steps?

Thanks.

**Comment by weavejester** [comment]
I don't know if it's even possible for Clojure deps tools to automatically add a `(require 'hashp.core)` to all projects in the same way Leiningen or Boot can.

Or are you asking how to require `hashp.core` manually? In which case, it's just `(require 'hashp.core)`.

**Comment by kirillsalykin** [comment]
I was interested in automated way. If it is not possible - shall I close the issue then?
(Maybe you can also specify in README that there is no way to automated use?)
Thanks.

**Comment by kirillsalykin** [comment]
UPD: there is already PR for this https://github.com/weavejester/hashp/pull/1. Closing the issue then.
